### ISSUE TITLE
M480BSP/SampleCode/StdDriver/DAC_EPWMTrigger/ ERROR Setting

### ISSUE THREAD

**Issue by David-lau** [OpenNuvoton/M480BSP#10]
in function SYS_Init:
/* Set PB multi-function pins for DAC voltage output */
SYS->**GPB_MFPL** |= SYS_GPB_MFPH_PB12MFP_DAC0_OUT | SYS_GPB_MFPH_PB13MFP_DAC1_OUT;
should be ?
SYS->**GPB_MFPH** |= SYS_GPB_MFPH_PB12MFP_DAC0_OUT | SYS_GPB_MFPH_PB13MFP_DAC1_OUT;

**Comment by yachen** [comment]
Hi, you're right. Do you like to send a pull request? Or prefer us to fix it directly?

**Comment by yachen** [comment]
Fixed in 9199a60, thanks.
