### ISSUE TITLE
I need a spi read SD chip code 

### ISSUE THREAD

**Issue by liruiyan** [OpenNuvoton/M480BSP#12]
there is no code, use spi read SD chip code . please help me , as soon as possable

**Comment by liruiyan** [comment]
use m480

**Comment by yachen** [comment]
Hi, 

There's a sample code in M0 BSP here. Although it's for Nano series, the SPI API are alike.
https://github.com/OpenNuvoton/Nano100B_BSP/tree/master/SampleCode/Nu-LB-NANO130/FATFS_SDCard

This sample code demonstrate how to access SD card using SPI interface.
