### ISSUE TITLE
M481ZIDAE cannot get UART1 to work 

### ISSUE THREAD

**Issue by Hoel** [OpenNuvoton/M480BSP#15]
Hi,
We are evaluating M481ZIDAE for a product to replace STM32F411 and i have to say the peripheral library and the toolchain really leave to be desired. We use NUEclipse and NuLink and there is not even a way to load and run the firmware directly without starting a debug session, this is really annoying, for the least, please let us know how to setup the run configuration so that the run button directly load and run the firmware without opening a debug session,  without that the productivity is deeply affected.

Other than that we have some issues with the BSP, at first it looked decent but as soon as we started to use it, it became clear that it was going to be a pain, basically it is full of defines which we have no way to know which one to use other than parsing sources or technical manual, it is really not how a peripheral library should be in 202 (maybe you should check how things are done by ST and other vendors).

That being said, here is the immediate problems we are facing now, starting with the M481ZIDAE : 

We need to use UART1 on PB2 and PB3 for printf, so we changed one of the example and the printf retarget to use UART1, sadly it does not work at all : 

```
#include <stdio.h>
#include "NuMicro.h"
#include "gpio.h"

#define PLL_CLOCK           192000000

void SYS_Init(void)
{
    /* Unlock protected registers */
    SYS_UnlockReg();

    /* Set XT1_OUT(PF.2) and XT1_IN(PF.3) to input mode */
    PF->MODE &= ~(GPIO_MODE_MODE2_Msk | GPIO_MODE_MODE3_Msk);

    /* Enable External XTAL (4~24 MHz) */
    CLK_EnableXtalRC(CLK_PWRCTL_HXTEN_Msk);

    /* Waiting for 12MHz clock ready */
    CLK_WaitClockReady(CLK_STATUS_HXTSTB_Msk);

    /* Set core clock as PLL_CLOCK from PLL */
    CLK_SetCoreClock(PLL_CLOCK);
    /* Set PCLK0/PCLK1 to HCLK/2 */
    CLK->PCLKDIV = (CLK_PCLKDIV_PCLK0DIV2 | CLK_PCLKDIV_PCLK1DIV2);

    /* Enable UART clock */
    CLK_EnableModuleClock(UART1_MODULE);
    CLK_EnableModuleClock(TMR0_MODULE);

    /* Select UART clock source from HXT */
    CLK_SetModuleClock(UART1_MODULE, CLK_CLKSEL1_UART1SEL_HXT, CLK_CLKDIV0_UART1(1));
    CLK_SetModuleClock(TMR0_MODULE, CLK_CLKSEL1_TMR0SEL_HXT, 0);

    /* Update System Core Clock */
    SystemCoreClockUpdate();

    /* Set PB multi-function pins for UART1 RXD(PB.2) and TXD(PB.3) */
    SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB2MFP_Msk)) | SYS_GPB_MFPL_PB2MFP_UART1_RXD;
    SYS->GPB_MFPL = (SYS->GPB_MFPL & (~SYS_GPB_MFPL_PB3MFP_Msk)) | SYS_GPB_MFPL_PB3MFP_UART1_TXD;

    /* Lock protected registers */
    SYS_LockReg();
}

int main()
{
    SYS_Init();
    SYS_ResetModule(UART1_RST);
    UART_Open(UART1, 115200);
    printf("\n\nCPU @ %dHz\n", SystemCoreClock);

    while(1){
    	printf("test uart1\n");
        TIMER_Delay(TIMER0, 200000);
    }
}
```

Also, we have a LED on PB15 and even getting this LED to blink doesnt work : 

```
#include <stdio.h>
#include "NuMicro.h"
#include "gpio.h"

#define PLL_CLOCK           192000000

void SYS_Init(void)
{
    /* Unlock protected registers */
    SYS_UnlockReg();

    /* Set XT1_OUT(PF.2) and XT1_IN(PF.3) to input mode */
    PF->MODE &= ~(GPIO_MODE_MODE2_Msk | GPIO_MODE_MODE3_Msk);

    /* Enable External XTAL (4~24 MHz) */
    CLK_EnableXtalRC(CLK_PWRCTL_HXTEN_Msk);

    /* Waiting for 12MHz clock ready */
    CLK_WaitClockReady(CLK_STATUS_HXTSTB_Msk);

    /* Set core clock as PLL_CLOCK from PLL */
    CLK_SetCoreClock(PLL_CLOCK);
    /* Set PCLK0/PCLK1 to HCLK/2 */
    CLK->PCLKDIV = (CLK_PCLKDIV_PCLK0DIV2 | CLK_PCLKDIV_PCLK1DIV2);

    /* Enable UART clock */
    CLK_EnableModuleClock(TMR0_MODULE);

    /* Update System Core Clock */
    /* User can use SystemCoreClockUpdate() to calculate SystemCoreClock. */
    SystemCoreClockUpdate();

    /* Lock protected registers */
    SYS_LockReg();
}

int main()
{
   SYS_Init();
   GPIO_SetMode(PB, BIT15, GPIO_MODE_OUTPUT);
    while(1){
        GPIO_TOGGLE(PB15);
        TIMER_Delay(TIMER0, 200000);
    }
}
```
Honestly i dont know how such simple things can be failing, and it is not very reassuring for the evaluation.
Ultimately what we need to do with this MCU is to have continuous acquisition of ADC samples via DMA at 12bit-1.6MSPS from differential input PB0 - PB1 into a 16KB (or 2*8KB) buffer, with interrupts at half and full transfer (hopefully there is a function to do double buffering too) and process the samples continuously during acquisition with the DSP library. We also need to use the I2C on PA2 - PA3 for control of an external chip. 

All that should be very simple, at least it is with the STM32F411 so i hope you guy can help us to setup the IDE and get that done.

**Comment by yachen** [comment]
Hi,

Regarding the 2 issues you listed here.

1. Did you define DEBUG_PORT as UART1 in Library\StdDriver\src\retarget.c?
2. Are you using Keil? I'm seeing following line been moved outside the while loop if optimization level 1 or above is selected. You might want to set #pragma O0 before the functions those contain tiny loops toggling GPIO. Not seeing this issue with IAR though.
```GPIO_TOGGLE(PB15);```


Sincerely,

Yi-An Chen

**Comment by Hoel** [comment]
Hi Chen,
Thank you for the prompt support.
The UART and GPIO problems are all solved now, the reason was on hardware side, specifically with the external 12MHZ crystal, as soon as it has been fixed the UART and GPIO (and I2C) worked fine.

1. yes, it was set to the corrrect UART.
2. As precised, we use NUEclipse.

Now the problems remaining are : 
1. NUEclipse run button 

-could you please let us know how to set the run configuration in Eclipse so that a press on the RUN button load the firmware into the M481 and run it without starting a debug session?

2. ADC acquisition via DMA into a 16KB buffer with VRef set to 1.6V internal.

We have not been able to find any clear example on how to set the ADC acquisition to continuous with software trigger, and setup the DMA for continuous acquisition into a 16KB buffer (ideally with double buffering of 2*8K since the 8K previous samples are processed while the current 8K samples are acquired).
-Could you please provide a snipet for that?

Thank you.

**Comment by yachen** [comment]
Hi,

1. NuEclipse run button
- Click "RUN" button on menu bar and select **Run Configuration**
- Double click **GDB Nuvoton Nu-Link Debugging group**
- Set your **Project** and **C/C++ Application** in Main tab
- Check **Erase Chip**, **Load Executable to flash** and **Continue** checkbox in Startup tab
- Click the **Run** button at the bottom

2. ADC acquisition via DMA into a 16KB buffer with VRef set to 1.6V internal.
- Set EADC software trigger source
```
    /* Configure the sample module 0 for analog input channel 0 and enable software trigger source */ 
    EADC_ConfigSampleModule(EADC, 0, EADC_SOFTWARE_TRIGGER, 0);
```
- Set Vref to 1.6V, this is a protected register, so you might want to put this code in SYS_Init
```
    /* Set reference voltage to external pin (1.6V) */
    SYS_SetVRef(SYS_VREFCTL_VREF_1_6V);
```
- PDMA ping-pong buffer using scatter-gather mode.
```
uint16_t g_au32DestArray0[8];
uint16_t g_au32DestArray1[8];
uint32_t g_u32DMAConfig = 0;

typedef struct dma_desc_t
{
    uint32_t ctl;
    uint32_t src;
    uint32_t dest;
    uint32_t offset;
} DMA_DESC_T;
DMA_DESC_T DMA_DESC[2];


   /* Open Channel 4 */
    PDMA_Open(PDMA,1 << 4);

    /* Enable Scatter Gather mode, assign the first scatter-gather descriptor table is table 1,
       and set transfer mode as EADC0_RX to memory */
    PDMA_SetTransferMode(PDMA,4, PDMA_EADC0_RX, TRUE, (uint32_t)&DMA_DESC[0]);

    /* Scatter-Gather descriptor table configuration in SRAM */
    g_u32DMAConfig = \
                     (7 << PDMA_DSCT_CTL_TXCNT_Pos) | /* Transfer count is 8 */ \
                     PDMA_WIDTH_16 |  /* Transfer width is 16 bits(one word) */ \
                     PDMA_SAR_FIX |   /* Source increment size is fixed(no increment) */ \
                     PDMA_DAR_INC |   /* Destination increment size is 16 bits */ \
                     PDMA_REQ_SINGLE | /* Transfer type is single transfer type */ \
                     PDMA_OP_SCATTER; /* Operation mode is scatter-gather mode */

   DMA_DESC[0].ctl = g_u32DMAConfig;
    /* Configure source address */
    DMA_DESC[0].src = (uint32_t)&EADC->DAT[0]; 
    /* Configure destination address */
    DMA_DESC[0].dest = (uint32_t)&g_au32DestArray0[0]; /* Ping-Pong buffer 1 */
    /* Configure next descriptor table address */
    DMA_DESC[0].offset = (uint32_t)&DMA_DESC[1] - (PDMA->SCATBA); /* next operation table is table 2 */

    DMA_DESC[1].ctl = g_u32DMAConfig;
    /* Configure source address */
    DMA_DESC[1].src = (uint32_t)&EADC->DAT[0]; 
    /* Configure destination address */
    DMA_DESC[1].dest = (uint32_t)&g_au32DestArray1[0]; /* Ping-Pong buffer 2 */
    /* Configure next descriptor table address */
    DMA_DESC[1].offset = (uint32_t)&DMA_DESC[0] - (PDMA->SCATBA); /* next operation table is table 1 */
```

Sincerely,

Yi-An Chen

**Comment by Hoel** [comment]
Hi Chen,
Thank you very much, it is beautiful, i must say Nuvoton support is pretty impressive 👍

**Comment by Hoel** [comment]
So i followed your indication for the run configuration, unfortunately it doesn't work, when i used this new configuration from the RUN menu it still launch a debug session as before.
I finally managed to find a solution:

- in **debugger** tab, at config options, paste the following after the two fist arguments;
 **-c "program Debug/test.elf verify reset exit"**
replace **test.elf** by the actual name of the binary

- in Startup tab, un-check everything

**Comment by yachen** [comment]
Hi,

Can you capture Main, Debugger, and Startup tabs and paste them here?
The method I provided works fine here, I'd like to check if there's other setting cause the difference. Thanks.

Sincerely,

Yi-An Chen

**Comment by Hoel** [comment]
OK i will try to do that later, as a side note there is some wrong hardcoded path in Nueclipse that prevent update : 
```
Some sites could not be found.  See the error log for more detail.
No repository found at jar:file:/C:/MyCode/NuEclipse/Git/plug-ins-3.4.1-201704251808/ilg.gnuarmeclipse-repository/target/ilg.gnuarmeclipse.repository-3.4.1-SNAPSHOT.zip!/.
No repository found at jar:file:/C:/MyCode/NuEclipse/Git/com.nuvoton.update/target/com.nuvoton.update-1.0.1-SNAPSHOT.zip!/.
```
The reason why i want to update is that the StdDriver library that comes with NuEclispe is out of date which cause problems (missing functions and defines etc>...)

Also are the ADC/DMA related functions correct? i have some doubt due to the fact i use differential rather than single end

```
void dma_init(void){

   /* Open Channel 4 */
	PDMA_Open(PDMA,1 << 4);

	/* Enable Scatter Gather mode, assign the first scatter-gather descriptor table is table 1,
	   and set transfer mode as EADC0_RX to memory */
	PDMA_SetTransferMode(PDMA,4, PDMA_EADC0_RX, TRUE, (uint32_t)&DMA_DESC[0]);

	/* Scatter-Gather descriptor table configuration in SRAM */
	g_u32DMAConfig = \
					 (7 << PDMA_DSCT_CTL_TXCNT_Pos) | /* Transfer count is 8 */ \
					 PDMA_WIDTH_16 |  /* Transfer width is 16 bits(one word) */ \
					 PDMA_SAR_FIX |   /* Source increment size is fixed(no increment) */ \
					 PDMA_DAR_INC |   /* Destination increment size is 16 bits */ \
					 PDMA_REQ_SINGLE | /* Transfer type is single transfer type */ \
					 PDMA_OP_SCATTER; /* Operation mode is scatter-gather mode */

    DMA_DESC[0].ctl = g_u32DMAConfig;
	/* Configure source address */
	DMA_DESC[0].src = (uint32_t)&EADC->DAT[0];
	/* Configure destination address */
	DMA_DESC[0].dest = (uint32_t)&g_au32DestArray0[0]; /* Ping-Pong buffer 1 */
	/* Configure next descriptor table address */
	DMA_DESC[0].offset = (uint32_t)&DMA_DESC[1] - (PDMA->SCATBA); /* next operation table is table 2 */

	DMA_DESC[1].ctl = g_u32DMAConfig;
	/* Configure source address */
	DMA_DESC[1].src = (uint32_t)&EADC->DAT[0];
	/* Configure destination address */
	DMA_DESC[1].dest = (uint32_t)&g_au32DestArray1[0]; /* Ping-Pong buffer 2 */
	/* Configure next descriptor table address */
	DMA_DESC[1].offset = (uint32_t)&DMA_DESC[0] - (PDMA->SCATBA); /* next operation table is table 1 */
}

void ADC_init(void)
{
	//Set Vref to 1.6V, this is a protected register
	SYS_SetVRef(SYS_VREFCTL_VREF_1_6V);

    /* Enable EADC module clock */
    CLK_EnableModuleClock(EADC_MODULE);

    /* EADC clock source is 96MHz, set divider to 8, EADC clock is 96/8 MHz */
    CLK_SetModuleClock(EADC_MODULE, 0, CLK_CLKDIV0_EADC(8));

    /* Configure the GPB0-GPB1 for ADC analog input pins.  */
    SYS->GPB_MFPL &= ~(SYS_GPB_MFPL_PB0MFP_Msk | SYS_GPB_MFPH_PB10MFP_Msk);
    SYS->GPB_MFPL |= SYS_GPB_MFPL_PB0MFP_EADC0_CH0 | SYS_GPB_MFPL_PB1MFP_EADC0_CH1;

    /* Disable the GPB9 digital input path to avoid the leakage current. */
    GPIO_DISABLE_DIGITAL_PATH(PB, BIT0);
    GPIO_DISABLE_DIGITAL_PATH(PB, BIT1);

    /* Set the ADC internal sampling time, input mode as differential and enable the A/D converter */
    EADC_Open(EADC, EADC_CTL_DIFFEN_DIFFERENTIAL);
    EADC_SetInternalSampleTime(EADC, 6);

    /* Configure the sample module 0 for analog input channel 0 and software trigger source.*/
    EADC_ConfigSampleModule(EADC, 0, EADC_SOFTWARE_TRIGGER, 0);

    //EADC_ENABLE_DOUBLE_BUFFER(eadc, u32ModuleNum)

    //Enable sample module 0 interrupt.
    //EADC_ENABLE_SAMPLE_MODULE_INT(EADC, 0, 0x1);

    /* Clear the A/D ADINT0 interrupt flag for safe */
    //EADC_CLR_INT_FLAG(EADC, 0x3);

    /* Enable the sample module 0 interrupt.  */
    //EADC_ENABLE_INT(EADC, 0x3);//Enable sample module A/D ADINT0 interrupt.
}
```

And to start the capture:

`EADC_START_CONV(EADC, 0x1); //Trigger sample module 0 to start A/D conversion`

**Comment by Hoel** [comment]
![image](https://user-images.githubusercontent.com/622955/91110760-11ace500-e67f-11ea-86d1-11ab5243a9be.png)
![image](https://user-images.githubusercontent.com/622955/91110777-1a9db680-e67f-11ea-8e43-1535dc1bc679.png)
![image](https://user-images.githubusercontent.com/622955/91110814-31440d80-e67f-11ea-8efa-3ab6271f5cc2.png)
![image](https://user-images.githubusercontent.com/622955/91110823-386b1b80-e67f-11ea-8ed1-a64b1c7223af.png)

**Comment by Hoel** [comment]
Also, how to have an interrupt generated at the end of the DMA transfer, once each buffer is filled?

**Comment by yachen** [comment]
Hi,

I cannot see flash been reprogrammed with now compiled image using your setting. Here's my setting:
![2020-08-25_11h40_07](https://user-images.githubusercontent.com/1320946/91120303-f0241b80-e6c7-11ea-8240-fb3eeec488c1.png)
![2020-08-25_11h40_29](https://user-images.githubusercontent.com/1320946/91120323-f9ad8380-e6c7-11ea-89b1-521e2f4db86f.png)
![2020-08-25_11h41_11](https://user-images.githubusercontent.com/1320946/91120331-fd410a80-e6c7-11ea-81ca-7da406634458.png)


Sincerely,

Yi-An Chen

**Comment by yachen** [comment]
Add following lines after the code we provided yesterday can let PDMA trigger interrupt after every scatter transfer complete.
```
    /* Enable transfer done interrupt */
    PDMA_EnableInt(PDMA,4, PDMA_INT_TRANS_DONE);
    NVIC_EnableIRQ(PDMA_IRQn);

```
Yes, this is the correct code to enable differential mode.
```
EADC_Open(EADC, EADC_CTL_DIFFEN_DIFFERENTIAL);
```
Please make sure this line is execute with register unlocked. (Refer to `SYS_UnlockReg();` and `SYS_LockReg();` in `SYS_Init()`)
```
SYS_SetVRef(SYS_VREFCTL_VREF_1_6V);
```

**Comment by Hoel** [comment]
i see the difference, you are in release mode.
About the run configuration i gave, it does work, but indeed it doesnt show log in the console, however on the right we can see the progression bar when its uploading.

**Comment by Hoel** [comment]
Hi,
So i added the handler for PDMA IRQ, also added EADC_ENABLE_PDMA(EADC); but still nothing, the PDMA interrupt seems to never get triggered. I add the whole test project attached, it  doesnt have any hardware dependency, could you please tell me what is wrong with the ADC/PDMA setup?
[test.zip](https://github.com/OpenNuvoton/M480BSP/files/5126611/test.zip)

There is also one information i couldnt get, how to know the base ADC conversion time (12bit)? i need to do the acquisition at 1.6MSPS exacttly, at first i used EADC_SetInternalSampleTime(EADC, 6); but this function doesnt exist anymore, so i found EADC_SetExtendSampleTime(EADC,0, 6); but it name suggests that this is an additional conversion time on top of the base conversion time, which i need to know in order to set the extended time and clock divider correctly for reaching 1.6MSPS.

**Comment by yachen** [comment]
Hi,

You didn't get any interrupt because the PDMA transfer count is 8 but only trigger ADC conversion once. Please see attached sample. But this method waste some CPU time to trigger ADC. 
Maybe it's better using EPWM to trigger ADC (refer to EADC_PDMA_EPWM_Trigger)?

[EADC_PDMA_ScatterGather_PingPongBuffer.zip](https://github.com/OpenNuvoton/M480BSP/files/5127443/EADC_PDMA_ScatterGather_PingPongBuffer.zip)

Sincerely,

Yi-An Chen

**Comment by Hoel** [comment]
i see, but it is not possible to retrigger the conversion, let along for each sample, in fact we cannot afford to have any interruption nor flag check during the transfer of each 8K samples block, and even re-triggering for each 8K block would be a problem because some samples would be lost.

I will look into EPWM but i dont really like the idea to have a PWM running during acquisition.
Is there no way to do continuous conversion and transfer for an defined (large) number of samples? 

on the STM32 we simply define the DMA buffer size to 16K : 
`if (HAL_ADC_Start_DMA(&hadc1, (uint32_t*) adcBfr, 1024*16) != HAL_OK) `
and from there the conversion is going forever, then we use half_complete and complete DMA transfer interrupts to process the correct half of the buffer while acquisition is continuing in the other half.
Re-trigger is never done unless we stop conversion manually.

**Comment by yachen** [comment]
Hi,

What's your concern about running a PWM at back ground? It's only use as a trigger source in your scenario. Don't have to output any waveform. This can trigger EADC at an accurate frequency.
Do you need exact 1.6MSPS? If not, another option is to use the EADC end of conversion interrupt signal to trigger next conversion. This trigger method takes few clock cycles to sync the interrupt signal to trigger next EADC conversion.


Sincerely,

Yi-An Chen

**Comment by Hoel** [comment]
My concern was indeed to have some IF signal pollution by the PWM, but it it doesnt output on any pin it should be fine.

the main points are : 
- accurate frequency (exactly 1.6MSPS)
- no cycles wasted by ADC/DMA management (because it is fully occupied by DSP processing) 
- no interrupts except when when the DMA transfer is half/full complete, meaning each 8K samples

**Comment by Hoel** [comment]
Hello, i am back on the M481 to test the EADC with PDMA and EPWM solution.
The goal is to capture continuously at 1.6MSPS (in 12bit mode) storing 8192 samples each time in two buffers (ping pong) so that one bufer can be processed while the other is storing.
I have refered to the EADC PDMA EPWM sample of the BSP but there is some points i cannot clarify yet : 

-How to set the EPWM clock configuration correctly to capture at 1.6MSPS

-What is the exact sample time of the ADC, because obviously i want to use the longest sample time achievable at 1.6MSPS to guarantee the best sampling. The only function i find is EADC_SetExtendSampleTime but, its unclear wether it sets the sample time, or some aditional cycles on top of the base samples time, which is itself unknown.

-how to set the ScatterGather thing to capture 8192 samples for PDMA, and should I use this mecanism to do the ping pong buffer switching, or do it myself with a "transfer complete" interrupt of PDMA (which i need anyway, to set some flag for the signal processing).
Thank you

**Comment by cwweng-nuvoton** [comment]
Hi,

You can set EPWM trigger EADC at 1.6MSPS by below two lines.
EPWM_ConfigOutputChannel(EPWM0, 0, 1600000, 50);
EPWM_EnableADCTrigger(EPWM0, 0, EPWM_TRG_ADC_EVEN_PERIOD);

EADC_SetExtendSampleTime () sets the additional sampling time.
For instance, EADC_SetExtendSampleTime(EADC, 0, 2); let EADC uses 2 additional clock for sampling at every conversion.

Attached is a sample code that EADC is triggered by EPWM at 1.6 MSPS. 
There are two 8KB ping-pong buffers for storing EADC conversion data. 
Two scatter gather tables describe transfer 4096 EADC data to buffer. (PDMA maximum transfer count is 4096)   
Both the two scatter gather tables finish transfer will generate a "PDMA transfer done" interrupt.
Therefore, you can set some flag in ISR for signal processing.

**Comment by cwweng-nuvoton** [comment]
Hi,

The sample code is as below.

[EADC_EPWMTrigger_PDMA_ScatterGather_PingPongBuffer.zip](https://github.com/OpenNuvoton/M480BSP/files/5174026/EADC_EPWMTrigger_PDMA_ScatterGather_PingPongBuffer.zip)

**Comment by Hoel** [comment]
Hi @cwweng-nuvoton  thank you very much 👍

**Comment by Hoel** [comment]
Hi @cwweng-nuvoton

I have implemented the signal processing chain currently used with the STM32F411 after modifying the buffer size to 8K (8192 samples, #define BUF_LEN   8192) since the processing chain expects that, and disabling loop counter, since it acquire continuously. I also have confirmed that the IF is indeed present in the buffer (value to 2048 when no signal and -2047 to 4096 when signal is present).
However the processing chain doesnt work, so something is wrong,

I suspect the interrupt is not occurring when i expect it, which is at the end of each 8192 sample transfer, could you confirm this point?
In the DMA interrupt we do 3 things:
- we set a volatile flag which is used to synchronize the processing chain with acquisition
- we assign the processing chain acquisition buffer pointer to the ADC buffer which has just been written
- we swap some pointer assignation for another FIFO  used further down in the processing chain.

These action must necessary take place immediately once a 8192 sample buffer is filled, Since the scatter-getter system is not very clear to me i suspect (and hope) that for some reason the DMA interrupt is not occurring when the 8192 samples have been acquired but maybe once the description table is finished or something like that...
Please kindly confirm this and if its the case let me know which interrupt i need. 

As a side note, i wonder wether there is a register to set a DC bias value for the ADC so that we dont have to compute the offset in the processing chain, that is if i give the value 2048, when the raw ADC reading is 2048 then the ADC value in the buffer is 0 (of course i use INT16 forr the ADC buffers).

**Comment by Hoel** [comment]
i used a GPIO to check timing between DMA interrupts with a scope and there is definitely something wrong, the time jumps between 880ns and 440ns, and it is not consistent, ie it doesnt alternate between 440ns and 880ns, The 880ns period is fairly steady but the 440ns period varies quite a lot, 650ns to 350ns.

**Comment by Hoel** [comment]
ok, this was actually not a problem, the cause was just the pointers assignations in the interrupt, for some reason it takes more cycles sometimes than others, anyway i moved that into the processing loop and only leaved the DMA flag in the interrupt handler, anyway this had no consequence on the period between DMA interrupts which is about 5.16 ms and constant, correct value for 1.6 MSPS. After more tweaking i got the processing chain to work, it turned out the M481 is so much faster than the STM32F411 (100MHz) i had to adjust some timeouts for preamble detection. Now it works nicely.
