### ISSUE TITLE
Examples for winusb?

### ISSUE THREAD

**Issue by gavinfree** [OpenNuvoton/M480BSP#17]
Hi,
    I am currently woking on using winusb on m480. I did notice some of the requirements but couldn't meet them all. So are there
any examples for m480 to enum using winusb that shows all the differences like adding bos descriptors,  responding to requests, etc.
   Thanks!

**Comment by yachen** [comment]
Hi,

I'm afraid we don't have winusb sample on M480. You might want to reference the VENDOR_LBK sample code. This is probably the the easiest sample to modify to adopt winusb.


Sincerely,

Yi-An Chen
