### ISSUE TITLE
Do qspi and spim switch their io2 and io3 pins?

### ISSUE THREAD

**Issue by gavinfree** [OpenNuvoton/M480BSP#19]
Hi, I am checking qspi in 4-wire mode and spim using m484sidae and find their io2 and io3 pins may be switched. Is that right?
![1](https://user-images.githubusercontent.com/21150848/100843265-115d8a80-34b5-11eb-875f-8e106d58c9ea.PNG)
![2](https://user-images.githubusercontent.com/21150848/100843275-13274e00-34b5-11eb-8b08-74b454ea81d1.PNG)

**Comment by yachen** [comment]
Not sure what do yo mean by "switched". But the pin definition shown on the figures are correct.

**Comment by gavinfree** [comment]
Well, I mean in QSPI, pin 26 mosi1 according to reference manual should be io2 in 4-wire spi, while in SPIM mode it is io3. That means they "switched".

**Comment by yachen** [comment]
Then yes, they are switched.

**Comment by gavinfree** [comment]
OK, thanks! By the way, the pin name of the qspi module is really confusing.
