### ISSUE TITLE
USB2.0 HUSBD WakeUp?

### ISSUE THREAD

**Issue by Alg-tech** [OpenNuvoton/M480BSP#25]
Can you provide a high speed USB device demo for remote wakeup

**Comment by ychuang3** [comment]
We have added demostration of remote wakeup function to sample HSUSBD_HID_Mouse.
Please refer to the lastest commit I6bc00b6965776e20aa15246af616f29b3b8c675b.

**Comment by Alg-tech** [comment]
Thank you very much
