### ISSUE TITLE
M483的CAN发送请求如何取消。

### ISSUE THREAD

**Issue by wall-xv** [OpenNuvoton/M480BSP#26]
1 比如在CAN断线的情况下，使用MSG(16)发送，这时发送不成功，等100ms后，还是不成功，这时如何取消这个发送请求。
2 出现这样的异常
In Hard Fault Handler
r0  = 0x200151b0
r1  = 0x20016238
r2  = 0x0
r3  = 0x2000014c
r12 = 0x0
lr  = 0x2000b8c0
pc  = 0x2000b8c0
psr = 0x6000000e
如何定位异常产生的地址

**Comment by mjchen1** [comment]
1 比如在CAN断线的情况下，使用MSG(16)发送，这时发送不成功，等100ms后，还是不成功，这时如何取消这个发送请求。
可以把control register(CAN_CON[5])的DAR設為"1",傳失敗後,就不會一直自動重傳

**Comment by wall-xv** [comment]
测试有效，谢谢
