### ISSUE TITLE
Cant run evaluationboard Nuvoton NuMaker-M483KG V1.1

### ISSUE THREAD

**Issue by TolunayOruc** [OpenNuvoton/M480BSP#27]
When running the sample code I get the following error in NuEclipse:

Open On-Chip Debugger 0.10.0-dev-00476-gd1de37d6-dirty (2021-12-08-10:03)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "hla_swd". To override use 'transport select <transport>'.
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
Info : clock speed 1000 kHz
Error: We cannot find any Nuvoton device. Please check the hardware connection.
Error: If the ICE is used by another Nuvoton tool, please close the connection between the ICE and Nuvoton tool.
in procedure 'init' 
in procedure 'ocd_bouncer'

I have connected the evaluation board with usb and have set Nu-Link2-Me VCOM Switch No. 1 and 2 to 
ON. Building works fine but when I debug I get this error.

**Comment by ccli0** [comment]
Hi TolunayOruc,

Please make sure the following items:
1. OpenOCD setup option is checked in the debugger tab of debug configurations and close other Nuvoton tool.
2. Please check the hardware connection.

If you still have problems, please fill in the -d3 in config options in the debugger tab of debug configurations to get more message.
-f ../scripts/interface/nulink.cfg -f ../scripts/target/numicroM4.cfg -d3

**Comment by TolunayOruc** [comment]
Hi,

Following the user manual and using FirstExample and the delivered BSP480 template sample code I get the following error code with both projects:

Open On-Chip Debugger 0.10.0-dev-00476-gd1de37d6-dirty (2021-12-08-10:03)
Licensed under GNU GPL v2
For bug reports, read
      http://openocd.org/doc/doxygen/bugs.html
User : 13 1 command.c:544 command_print(): debug_level: 3
Debug: 14 2 options.c:166 add_default_dirs(): bindir=bin
Debug: 15 2 options.c:167 add_default_dirs(): pkgdatadir=
Debug: 16 2 options.c:168 add_default_dirs(): run_prefix=C:/Program Files (x86)/Nuvoton Tools/NuEclipse/V1.01.019/NuEclipse/eclipse/OpenOCD
Debug: 17 2 configuration.c:42 add_script_search_dir(): adding C:\Users\toruc\AppData\Roaming/OpenOCD
Debug: 18 3 configuration.c:42 add_script_search_dir(): adding C:/Program Files (x86)/Nuvoton Tools/NuEclipse/V1.01.019/NuEclipse/eclipse/OpenOCD/site
Debug: 19 3 configuration.c:42 add_script_search_dir(): adding C:/Program Files (x86)/Nuvoton Tools/NuEclipse/V1.01.019/NuEclipse/eclipse/OpenOCD/scripts
Debug: 20 5 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_gdb_port 3333
Debug: 21 5 command.c:143 script_debug(): command - gdb_port ocd_gdb_port 3333
Debug: 23 5 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_telnet_port 4444
Debug: 24 5 command.c:143 script_debug(): command - telnet_port ocd_telnet_port 4444
Debug: 26 6 configuration.c:82 find_file(): found C:/Program Files (x86)/Nuvoton Tools/NuEclipse/V1.01.019/NuEclipse/eclipse/OpenOCD/site/../scripts/interface/nulink.cfg
Debug: 27 8 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_interface hla
Debug: 28 8 command.c:143 script_debug(): command - interface ocd_interface hla
Debug: 30 8 command.c:364 register_command_handler(): registering 'ocd_hla_device_desc'...
Debug: 31 8 command.c:364 register_command_handler(): registering 'ocd_hla_serial'...
Debug: 32 8 command.c:364 register_command_handler(): registering 'ocd_hla_layout'...
Debug: 33 8 command.c:364 register_command_handler(): registering 'ocd_hla_close'...
Debug: 34 9 command.c:364 register_command_handler(): registering 'ocd_hla_reset'...
Debug: 35 9 command.c:364 register_command_handler(): registering 'ocd_hla_vid_pid'...
Debug: 36 9 command.c:364 register_command_handler(): registering 'ocd_hla_vids_pids'...
Debug: 37 9 command.c:364 register_command_handler(): registering 'ocd_hla_command'...
Debug: 38 9 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_hla_layout nulink
Debug: 39 9 command.c:143 script_debug(): command - hla_layout ocd_hla_layout nulink
Debug: 41 10 hla_interface.c:239 hl_interface_handle_layout_command(): hl_interface_handle_layout_command
Debug: 42 10 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_hla_vids_pids 0x0416 0x511b 0x0416 0x511c 0x0416 0x511d
Debug: 43 10 command.c:143 script_debug(): command - hla_vids_pids ocd_hla_vids_pids 0x0416 0x511b 0x0416 0x511c 0x0416 0x511d
Debug: 45 10 hla_interface.c:312 hl_interface_handle_vids_pids_command(): hl_interface_handle_vids_pids_command
Debug: 46 10 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_hla_device_desc Nu-Link
Debug: 47 11 command.c:143 script_debug(): command - hla_device_desc ocd_hla_device_desc Nu-Link
Debug: 49 11 hla_interface.c:213 hl_interface_handle_device_desc_command(): hl_interface_handle_device_desc_command
Debug: 50 11 configuration.c:82 find_file(): found C:/Program Files (x86)/Nuvoton Tools/NuEclipse/V1.01.019/NuEclipse/eclipse/OpenOCD/site/../scripts/target/numicroM4.cfg
Debug: 51 12 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_transport select
Debug: 52 12 command.c:143 script_debug(): command - ocd_transport ocd_transport select
Info : 53 12 transport.c:285 jim_transport_select(): auto-selecting first available session transport "hla_swd". To override use 'transport select <transport>'.
Debug: 54 12 hla_transport.c:191 hl_transport_select(): hl_transport_select
Debug: 55 12 command.c:364 register_command_handler(): registering 'ocd_hla'...
Debug: 56 13 command.c:364 register_command_handler(): registering 'ocd_jtag'...
Debug: 57 13 command.c:364 register_command_handler(): registering 'ocd_jtag'...
Debug: 58 13 command.c:364 register_command_handler(): registering 'ocd_jtag'...
Debug: 59 13 command.c:364 register_command_handler(): registering 'ocd_jtag'...
Debug: 60 13 command.c:364 register_command_handler(): registering 'ocd_jtag'...
Debug: 61 13 command.c:364 register_command_handler(): registering 'ocd_jtag'...
Debug: 62 13 command.c:364 register_command_handler(): registering 'ocd_jtag'...
Debug: 63 13 command.c:364 register_command_handler(): registering 'ocd_jtag'...
Debug: 64 14 command.c:364 register_command_handler(): registering 'ocd_jtag'...
Debug: 65 14 command.c:364 register_command_handler(): registering 'ocd_jtag_ntrst_delay'...
Debug: 66 14 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_transport select
Debug: 67 14 command.c:143 script_debug(): command - ocd_transport ocd_transport select
Debug: 68 14 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_transport select
Debug: 69 14 command.c:143 script_debug(): command - ocd_transport ocd_transport select
Debug: 70 15 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_transport select
Debug: 71 15 command.c:143 script_debug(): command - ocd_transport ocd_transport select
Debug: 72 15 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_hla newtap NuMicro cpu -irlen 4 -expected-id 0x2BA01477
Debug: 73 15 command.c:143 script_debug(): command - ocd_hla ocd_hla newtap NuMicro cpu -irlen 4 -expected-id 0x2BA01477
Debug: 74 15 hla_tcl.c:115 jim_hl_newtap_cmd(): Creating New Tap, Chip: NuMicro, Tap: cpu, Dotted: NuMicro.cpu, 4 params
Debug: 75 16 hla_tcl.c:126 jim_hl_newtap_cmd(): Processing option: -irlen
Debug: 76 16 hla_tcl.c:126 jim_hl_newtap_cmd(): Processing option: -expected-id
Debug: 77 16 core.c:1300 jtag_tap_init(): Created Tap: NuMicro.cpu @ abs position 0, irlen 0, capture: 0x0 mask: 0x0
Debug: 78 16 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_target create NuMicro.cpu cortex_m -chain-position NuMicro.cpu
Debug: 79 16 command.c:143 script_debug(): command - ocd_target ocd_target create NuMicro.cpu cortex_m -chain-position NuMicro.cpu
Debug: 80 17 nulink_usb.c:1356 nulink_usb_override_target(): nulink_usb_override_target
Info : 81 17 target.c:5256 target_create(): The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
Debug: 82 17 target.c:1892 target_free_all_working_areas_restore(): freeing all working areas
Debug: 83 17 command.c:364 register_command_handler(): registering 'ocd_arm'...
Debug: 84 17 command.c:364 register_command_handler(): registering 'ocd_arm'...
Debug: 85 17 command.c:364 register_command_handler(): registering 'ocd_arm'...
Debug: 86 18 command.c:364 register_command_handler(): registering 'ocd_arm'...
Debug: 87 18 command.c:364 register_command_handler(): registering 'ocd_arm'...
Debug: 88 18 command.c:364 register_command_handler(): registering 'ocd_arm'...
Debug: 89 18 command.c:364 register_command_handler(): registering 'ocd_tpiu'...
Debug: 90 18 command.c:364 register_command_handler(): registering 'ocd_itm'...
Debug: 91 18 command.c:364 register_command_handler(): registering 'ocd_itm'...
Debug: 92 18 hla_target.c:351 adapter_target_create(): adapter_target_create
Debug: 93 18 hla_target.c:322 adapter_init_arch_info(): adapter_init_arch_info
Debug: 94 19 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 95 19 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 96 19 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 97 19 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 98 19 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 99 19 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 100 19 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 101 20 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 102 20 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 103 20 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 104 20 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 105 20 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 106 20 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 107 20 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 108 21 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 109 21 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 110 21 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 111 21 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 112 21 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 113 21 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 114 21 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 115 22 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 116 22 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 117 22 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 118 22 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 119 22 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 120 22 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 121 22 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 122 23 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 123 23 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 124 23 command.c:364 register_command_handler(): registering 'ocd_NuMicro.cpu'...
Debug: 125 23 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_NuMicro.cpu configure -work-area-phys 0x20000000 -work-area-size 0x4000 -work-area-backup 0
Debug: 126 24 command.c:143 script_debug(): command - ocd_NuMicro.cpu ocd_NuMicro.cpu configure -work-area-phys 0x20000000 -work-area-size 0x4000 -work-area-backup 0
Debug: 127 24 target.c:1892 target_free_all_working_areas_restore(): freeing all working areas
Debug: 128 24 target.c:1892 target_free_all_working_areas_restore(): freeing all working areas
Debug: 129 25 target.c:1892 target_free_all_working_areas_restore(): freeing all working areas
Debug: 130 25 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_flash bank NuMicro.flash_aprom numicro 0x00000000 0 0 0 NuMicro.cpu
Debug: 131 25 command.c:143 script_debug(): command - ocd_flash ocd_flash bank NuMicro.flash_aprom numicro 0x00000000 0 0 0 NuMicro.cpu
Debug: 133 25 command.c:364 register_command_handler(): registering 'ocd_numicro'...
Debug: 134 26 command.c:364 register_command_handler(): registering 'ocd_numicro'...
Debug: 135 26 command.c:364 register_command_handler(): registering 'ocd_numicro'...
Debug: 136 26 command.c:319 command_new(): BUG: command 'numicro chip_erase' does not have the '.usage' field filled out
Debug: 137 26 command.c:364 register_command_handler(): registering 'ocd_numicro'...
Debug: 138 26 command.c:319 command_new(): BUG: command 'numicro M2351_erase' does not have the '.usage' field filled out
Debug: 139 27 command.c:364 register_command_handler(): registering 'ocd_numicro'...
Debug: 140 27 command.c:319 command_new(): BUG: command 'numicro NUC505_sram_ini' does not have the '.usage' field filled out
Debug: 141 27 command.c:364 register_command_handler(): registering 'ocd_numicro'...
Debug: 142 27 command.c:319 command_new(): BUG: command 'numicro NUC505_chip_reset' does not have the '.usage' field filled out
Debug: 143 28 command.c:364 register_command_handler(): registering 'ocd_numicro'...
Debug: 144 28 numicro.c:3933 numicro_flash_bank_command(): add flash_bank numicro NuMicro.flash_aprom
Debug: 145 28 tcl.c:1032 handle_flash_bank_command(): 'numicro' driver usage field missing
Debug: 146 28 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_flash bank NuMicro.flash_data numicro 0x0001F000 0 0 0 NuMicro.cpu
Debug: 147 29 command.c:143 script_debug(): command - ocd_flash ocd_flash bank NuMicro.flash_data numicro 0x0001F000 0 0 0 NuMicro.cpu
Debug: 149 29 command.c:398 register_command(): command 'numicro' is already registered in '<global>' context
Debug: 150 29 command.c:398 register_command(): command 'read_isp' is already registered in 'numicro' context
Debug: 151 30 command.c:398 register_command(): command 'write_isp' is already registered in 'numicro' context
Debug: 152 30 command.c:398 register_command(): command 'erase_isp' is already registered in 'numicro' context
Debug: 153 30 command.c:398 register_command(): command 'chip_erase' is already registered in 'numicro' context
Debug: 154 30 command.c:398 register_command(): command 'M2351_erase' is already registered in 'numicro' context
Debug: 155 31 command.c:398 register_command(): command 'NUC505_sram_ini' is already registered in 'numicro' context
Debug: 156 31 command.c:398 register_command(): command 'NUC505_chip_reset' is already registered in 'numicro' context
Debug: 157 31 numicro.c:3933 numicro_flash_bank_command(): add flash_bank numicro NuMicro.flash_data
Debug: 158 31 tcl.c:1032 handle_flash_bank_command(): 'numicro' driver usage field missing
Debug: 159 31 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_flash bank NuMicro.flash_ldrom numicro 0x00100000 0 0 0 NuMicro.cpu
Debug: 160 32 command.c:143 script_debug(): command - ocd_flash ocd_flash bank NuMicro.flash_ldrom numicro 0x00100000 0 0 0 NuMicro.cpu
Debug: 162 32 command.c:398 register_command(): command 'numicro' is already registered in '<global>' context
Debug: 163 32 command.c:398 register_command(): command 'read_isp' is already registered in 'numicro' context
Debug: 164 32 command.c:398 register_command(): command 'write_isp' is already registered in 'numicro' context
Debug: 165 32 command.c:398 register_command(): command 'erase_isp' is already registered in 'numicro' context
Debug: 166 33 command.c:398 register_command(): command 'chip_erase' is already registered in 'numicro' context
Debug: 167 33 command.c:398 register_command(): command 'M2351_erase' is already registered in 'numicro' context
Debug: 168 33 command.c:398 register_command(): command 'NUC505_sram_ini' is already registered in 'numicro' context
Debug: 169 33 command.c:398 register_command(): command 'NUC505_chip_reset' is already registered in 'numicro' context
Debug: 170 33 numicro.c:3933 numicro_flash_bank_command(): add flash_bank numicro NuMicro.flash_ldrom
Debug: 171 33 tcl.c:1032 handle_flash_bank_command(): 'numicro' driver usage field missing
Debug: 172 34 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_flash bank NuMicro.flash_config numicro 0x00300000 0 0 0 NuMicro.cpu
Debug: 173 34 command.c:143 script_debug(): command - ocd_flash ocd_flash bank NuMicro.flash_config numicro 0x00300000 0 0 0 NuMicro.cpu
Debug: 175 34 command.c:398 register_command(): command 'numicro' is already registered in '<global>' context
Debug: 176 34 command.c:398 register_command(): command 'read_isp' is already registered in 'numicro' context
Debug: 177 35 command.c:398 register_command(): command 'write_isp' is already registered in 'numicro' context
Debug: 178 35 command.c:398 register_command(): command 'erase_isp' is already registered in 'numicro' context
Debug: 179 35 command.c:398 register_command(): command 'chip_erase' is already registered in 'numicro' context
Debug: 180 35 command.c:398 register_command(): command 'M2351_erase' is already registered in 'numicro' context
Debug: 181 35 command.c:398 register_command(): command 'NUC505_sram_ini' is already registered in 'numicro' context
Debug: 182 35 command.c:398 register_command(): command 'NUC505_chip_reset' is already registered in 'numicro' context
Debug: 183 36 numicro.c:3933 numicro_flash_bank_command(): add flash_bank numicro NuMicro.flash_config
Debug: 184 36 tcl.c:1032 handle_flash_bank_command(): 'numicro' driver usage field missing
Debug: 185 36 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_flash bank NuMicro.flash_dfmc_data numicro 0x00400000 0 0 0 NuMicro.cpu
Debug: 186 36 command.c:143 script_debug(): command - ocd_flash ocd_flash bank NuMicro.flash_dfmc_data numicro 0x00400000 0 0 0 NuMicro.cpu
Debug: 188 36 command.c:398 register_command(): command 'numicro' is already registered in '<global>' context
Debug: 189 37 command.c:398 register_command(): command 'read_isp' is already registered in 'numicro' context
Debug: 190 37 command.c:398 register_command(): command 'write_isp' is already registered in 'numicro' context
Debug: 191 37 command.c:398 register_command(): command 'erase_isp' is already registered in 'numicro' context
Debug: 192 37 command.c:398 register_command(): command 'chip_erase' is already registered in 'numicro' context
Debug: 193 37 command.c:398 register_command(): command 'M2351_erase' is already registered in 'numicro' context
Debug: 194 37 command.c:398 register_command(): command 'NUC505_sram_ini' is already registered in 'numicro' context
Debug: 195 38 command.c:398 register_command(): command 'NUC505_chip_reset' is already registered in 'numicro' context
Debug: 196 38 numicro.c:3933 numicro_flash_bank_command(): add flash_bank numicro NuMicro.flash_dfmc_data
Debug: 197 38 tcl.c:1032 handle_flash_bank_command(): 'numicro' driver usage field missing
Debug: 198 38 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_adapter_khz 1000
Debug: 199 38 command.c:143 script_debug(): command - adapter_khz ocd_adapter_khz 1000
Debug: 201 39 core.c:1631 jtag_config_khz(): handle jtag khz
Debug: 202 39 core.c:1598 adapter_khz_to_speed(): convert khz to interface specific speed value
Debug: 203 39 core.c:1598 adapter_khz_to_speed(): convert khz to interface specific speed value
Debug: 204 39 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_reset_config none
Debug: 205 39 command.c:143 script_debug(): command - reset_config ocd_reset_config none
Debug: 207 39 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_transport select
Debug: 208 40 command.c:143 script_debug(): command - ocd_transport ocd_transport select
Debug: 209 40 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_NuMicro.cpu configure -event gdb-detach  exitDebugging
Debug: 210 40 command.c:143 script_debug(): command - ocd_NuMicro.cpu ocd_NuMicro.cpu configure -event gdb-detach  exitDebugging
Debug: 211 42 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_init
Debug: 212 42 command.c:143 script_debug(): command - init ocd_init
Debug: 214 42 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_target init
Debug: 215 43 command.c:143 script_debug(): command - ocd_target ocd_target init
Debug: 217 43 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_target names
Debug: 218 43 command.c:143 script_debug(): command - ocd_target ocd_target names
Debug: 219 43 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_NuMicro.cpu cget -event gdb-flash-erase-start
Debug: 220 44 command.c:143 script_debug(): command - ocd_NuMicro.cpu ocd_NuMicro.cpu cget -event gdb-flash-erase-start
Debug: 221 44 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_NuMicro.cpu configure -event gdb-flash-erase-start reset init
Debug: 222 44 command.c:143 script_debug(): command - ocd_NuMicro.cpu ocd_NuMicro.cpu configure -event gdb-flash-erase-start reset init
Debug: 223 44 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_NuMicro.cpu cget -event gdb-flash-write-end
Debug: 224 45 command.c:143 script_debug(): command - ocd_NuMicro.cpu ocd_NuMicro.cpu cget -event gdb-flash-write-end
Debug: 225 45 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_NuMicro.cpu configure -event gdb-flash-write-end reset halt
Debug: 226 45 command.c:143 script_debug(): command - ocd_NuMicro.cpu ocd_NuMicro.cpu configure -event gdb-flash-write-end reset halt
Debug: 227 45 target.c:1317 handle_target_init_command(): Initializing targets...
Debug: 228 46 hla_target.c:341 adapter_init_target(): adapter_init_target
Debug: 229 46 command.c:364 register_command_handler(): registering 'ocd_target_request'...
Debug: 230 46 command.c:364 register_command_handler(): registering 'ocd_trace'...
Debug: 231 46 command.c:364 register_command_handler(): registering 'ocd_trace'...
Debug: 232 46 command.c:364 register_command_handler(): registering 'ocd_fast_load_image'...
Debug: 233 46 command.c:364 register_command_handler(): registering 'ocd_fast_load'...
Debug: 234 47 command.c:364 register_command_handler(): registering 'ocd_profile'...
Debug: 235 47 command.c:364 register_command_handler(): registering 'ocd_virt2phys'...
Debug: 236 47 command.c:364 register_command_handler(): registering 'ocd_reg'...
Debug: 237 47 command.c:364 register_command_handler(): registering 'ocd_poll'...
Debug: 238 47 command.c:364 register_command_handler(): registering 'ocd_wait_halt'...
Debug: 239 47 command.c:364 register_command_handler(): registering 'ocd_halt'...
Debug: 240 47 command.c:364 register_command_handler(): registering 'ocd_resume'...
Debug: 241 47 command.c:364 register_command_handler(): registering 'ocd_reset'...
Debug: 242 48 command.c:364 register_command_handler(): registering 'ocd_soft_reset_halt'...
Debug: 243 48 command.c:364 register_command_handler(): registering 'ocd_step'...
Debug: 244 48 command.c:364 register_command_handler(): registering 'ocd_mdw'...
Debug: 245 48 command.c:364 register_command_handler(): registering 'ocd_mdh'...
Debug: 246 48 command.c:364 register_command_handler(): registering 'ocd_mdb'...
Debug: 247 48 command.c:364 register_command_handler(): registering 'ocd_mww'...
Debug: 248 48 command.c:364 register_command_handler(): registering 'ocd_mwh'...
Debug: 249 48 command.c:364 register_command_handler(): registering 'ocd_mwb'...
Debug: 250 49 command.c:364 register_command_handler(): registering 'ocd_bp'...
Debug: 251 49 command.c:364 register_command_handler(): registering 'ocd_rbp'...
Debug: 252 49 command.c:364 register_command_handler(): registering 'ocd_wp'...
Debug: 253 49 command.c:364 register_command_handler(): registering 'ocd_rwp'...
Debug: 254 49 command.c:364 register_command_handler(): registering 'ocd_load_image'...
Debug: 255 49 command.c:364 register_command_handler(): registering 'ocd_dump_image'...
Debug: 256 49 command.c:364 register_command_handler(): registering 'ocd_verify_image'...
Debug: 257 50 command.c:364 register_command_handler(): registering 'ocd_test_image'...
Debug: 258 50 command.c:364 register_command_handler(): registering 'ocd_reset_nag'...
Debug: 259 50 command.c:364 register_command_handler(): registering 'ocd_ps'...
Debug: 260 50 command.c:364 register_command_handler(): registering 'ocd_test_mem_access'...
Debug: 261 50 hla_interface.c:109 hl_interface_init(): hl_interface_init
Debug: 262 50 hla_layout.c:89 hl_layout_init(): hl_layout_init
Debug: 263 50 core.c:1598 adapter_khz_to_speed(): convert khz to interface specific speed value
Debug: 264 50 core.c:1601 adapter_khz_to_speed(): have interface set up
Debug: 265 51 nulink_usb.c:1366 nulink_speed(): nulink_speed: query(1)
Debug: 266 51 nulink_usb.c:1385 nulink_speed(): NULINK nulink_speed: 1000
Debug: 267 51 core.c:1598 adapter_khz_to_speed(): convert khz to interface specific speed value
Debug: 268 51 core.c:1601 adapter_khz_to_speed(): have interface set up
Debug: 269 51 nulink_usb.c:1366 nulink_speed(): nulink_speed: query(1)
Debug: 270 51 nulink_usb.c:1385 nulink_speed(): NULINK nulink_speed: 1000
Info : 271 51 core.c:1386 adapter_init(): clock speed 1000 kHz
Debug: 272 51 openocd.c:137 handle_init_command(): Debug Adapter init complete
Debug: 273 52 command.c:143 script_debug(): command - ocd_command ocd_command type ocd_transport init
Debug: 274 52 command.c:143 script_debug(): command - ocd_transport ocd_transport init
Debug: 276 52 transport.c:239 handle_transport_init(): handle_transport_init
Debug: 277 52 hla_transport.c:152 hl_transport_init(): hl_transport_init
Debug: 278 52 hla_transport.c:169 hl_transport_init(): current transport hla_swd
Debug: 279 52 hla_interface.c:42 hl_interface_open(): hl_interface_open
Debug: 280 52 hla_layout.c:40 hl_layout_open(): hl_layout_open
Debug: 281 52 nulink_usb.c:1465 nulink_usb_open(): nulink_usb_open
Debug: 282 53 nulink_usb.c:1472 nulink_usb_open(): Stat Case 1: -1
Debug: 283 53 nulink_usb.c:1496 nulink_usb_open(): Stat Case 2: 0
Debug: 284 163 nulink_usb.c:1500 nulink_usb_open(): Run NuLink.exe on Win64 (result: -6)
Debug: 285 165 nulink_usb.c:1507 nulink_usb_open(): Cannot find a target chip! (result: -6)
Error: 286 165 nulink_usb.c:1508 nulink_usb_open(): We cannot find any Nuvoton device. Please check the hardware connection.
Error: 287 165 nulink_usb.c:1509 nulink_usb_open(): If the ICE is used by another Nuvoton tool, please close the connection between the ICE and Nuvoton tool.
Debug: 288 166 hla_layout.c:47 hl_layout_open(): failed
Debug: 289 166 command.c:626 run_command(): Command failed with error code -4
User : 290 166 command.c:687 command_run_line(): in procedure 'init'
in procedure 'ocd_bouncer'
Debug: 291 167 command.c:626 run_command(): Command failed with error code -4
User : 292 167 command.c:687 command_run_line():
Debug: 293 167 hla_interface.c:117 hl_interface_quit(): hl_interface_quit
Debug: 294 167 nulink_usb.c:1431 nulink_usb_close(): nulink_usb_close

I have used the user manual also for the setup of the debugger and this is mine setup:

***@***.***

With kind regards.

Tolunay Oruc
Mastervolt

**Comment by ccli0** [comment]
Hi TolunayOruc,

Nu-Link2-Me cannot find any Nuvoton device on your PC. Do you check the hardware connection?
Or you can use KEIL or other Nuvoton tool to check the connection.
e.g. NuMicro ICP Programming Tool
https://www.nuvoton.com/tool-and-software/software-tool/programmer-tool/index.html

**Comment by TolunayOruc** [comment]
Hi,

When using NuMicro ICP Programming Tool it crashes when I click on connect. On Keil it opens on default with M487 when opening the template project. This doesn’t match mine M483. When I change this it crashes when downloading to flash memory. On mine computer I can see the following:

***@***.***

**Comment by TolunayOruc** [comment]
Hi,

The problem was a broken usb cable. Because of that it was able to show up in device manager but didn’t connect in the tools. Thankyou for the fast reply and help!

With kind regards,
Tolunay Oruc
Mastervolt
