### ISSUE TITLE
AES testing failed, when run sample code "test_suit_aes" always get failed result

### ISSUE THREAD

**Issue by KunYi** [OpenNuvoton/M480BSP#28]
run [M480BSP/SampleCode/Crypto_MbedTLS/test_suit_aes/KEIL/mbedtls_test_suit_aes.uvproj](https://github.com/OpenNuvoton/M480BSP/blob/master/SampleCode/Crypto_MbedTLS/test_suit_aes/KEIL/mbedtls_test_suit_aes.uvproj) on  NuMaker-PFM-M487
always get failed test result.

I try modify config.h to disable hardware accelerate function the result will test passed

**Comment by ychuang3** [comment]
This issue is caused by AES key modified by mbedtls S/W key processing. 
We should skip the mbedtls AES key processing when H/W AES enabled.
The lastest patch fixed this issue.

**Comment by KunYi** [comment]
Great job!
