### ISSUE TITLE
HSUSBD_RNDIS example  do not work

### ISSUE THREAD

**Issue by nongxiaoming** [OpenNuvoton/M480BSP#3]
HSUSBD_RNDIS example  do not work on theNuMaker-PFM-M487 board. I test on windows 7 and installation driver failed.

**Comment by yachen** [comment]
Hi,

Which driver did you install?

Sincerely,

Yi-An Chen

**Comment by nongxiaoming** [comment]
The driver which I install is Microsoft RNDIS driver on windows 7. I can't found any driver with nuvoton for it.

**Comment by yachen** [comment]
Hi,

So Windows report driver installation failed? Or cannot enable RNDIS interface after installed the driver? 

Sincerely,

Yi-An Chen
