### ISSUE TITLE
EADC DMA with EPWM trigger doesn't  stop by calling  EPWM_STOP()

### ISSUE THREAD

**Issue by lobra07** [OpenNuvoton/M480BSP#32]
EADC is setup with PDMA and EPWM trigger with scatter gather enabled 
everything works good but when i try to stop the EPWM by calling **EPWM_STOP()** the PDMA continue to request data 
and EADC continue to work 
but if i write the EPWMn->CNTEN &= ~(BITx) every thing works very good

**Comment by cwweng-nuvoton** [comment]
Following is the recommended procedure to stop EPWM channel n.
1. EPWM_Stop(EPWM0, EPWM_CH_n_MASK);  /* Set EPWM0 PERIOD n to 0 */
2. while((EPWM0->CNT[n] & EPWM_CNTn_CNT_Msk) != 0);  /* Wait until EPWM0 channel n current counter reach to 0 */
3. EPWM_ForceStop(EPWM0, EPWM_CH_n_MASK); /* Set EPWM CNTEN bit n to 0 */

The procedure will let EPWM counter continue count to 0 to finish a period counting. And then stop counting.
If you want to stop counting immediately, you can call **EPWM_ForceStop**(EPWM0, EPWM_CH_n_MASK);
