### ISSUE TITLE
SHA256 results, do not match with other SHA256 implementation

### ISSUE THREAD

**Issue by viobiscu** [OpenNuvoton/M480BSP#38]
I use the example provided under \SampleCode\StdDrive\CRYPTO_SHA to hash a test string and compare it with the 
SHA256 is implemented in SQL Server and some free online tools.

The hash does not match!

Not sure what am I doing wrong, bellow  is the code:

`//code
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "NuMicro.h"

static volatile int g_SHA_done;

void CRYPTO_IRQHandler()
{
    if (SHA_GET_INT_FLAG(CRPT))
    {
        g_SHA_done = 1;
        SHA_CLR_INT_FLAG(CRPT);
    }
}

int  run_sha(uint8_t * Data, uint32_t SizeBytes, uint32_t * au32OutputDigest)
{
    uint32_t u32SrcAddr = (uint32_t)&Data[0];
    SHA_Open(CRPT, SHA_MODE_SHA256, SHA_OUT_SWAP, 0); 
    SHA_SetDMATransfer(CRPT, u32SrcAddr,  SizeBytes);
    g_SHA_done = 0;
    SHA_Start(CRPT, CRYPTO_DMA_ONE_SHOT);
    while (!g_SHA_done) ;

    SHA_Read(CRPT, au32OutputDigest);

    return 0;
}

void SYS_Init(void)
{
    /* Unlock protected registers */
    SYS_UnlockReg();

    /* Set XT1_OUT(PF.2) and XT1_IN(PF.3) to input mode */
    PF->MODE &= ~(GPIO_MODE_MODE2_Msk | GPIO_MODE_MODE3_Msk);

    /* Enable HXT clock */
    CLK_EnableXtalRC(CLK_PWRCTL_HXTEN_Msk);

    /* Wait for HXT clock ready */
    CLK_WaitClockReady(CLK_STATUS_HXTSTB_Msk);

    /* Switch HCLK clock source to HXT */
    CLK_SetHCLK(CLK_CLKSEL0_HCLKSEL_HXT,CLK_CLKDIV0_HCLK(1));

    /* Set core clock as PLL_CLOCK from PLL */
    CLK_SetCoreClock(FREQ_192MHZ);

    /* Set both PCLK0 and PCLK1 as HCLK/2 */
    CLK->PCLKDIV = CLK_PCLKDIV_APB0DIV_DIV2 | CLK_PCLKDIV_APB1DIV_DIV2;

    /* Enable UART module clock */
    CLK_EnableModuleClock(UART0_MODULE);

    /* Select UART module clock source as HXT and UART module clock divider as 1 */
    CLK_SetModuleClock(UART0_MODULE, CLK_CLKSEL1_UART0SEL_HXT, CLK_CLKDIV0_UART0(1));

    /* Enable CRYPTO module clock */
    CLK_EnableModuleClock(CRPT_MODULE);

    /* Update System Core Clock */
    SystemCoreClockUpdate();

    /* Set GPB multi-function pins for UART0 RXD and TXD */
    SYS->GPB_MFPH &= ~(SYS_GPB_MFPH_PB12MFP_Msk | SYS_GPB_MFPH_PB13MFP_Msk);
    SYS->GPB_MFPH |= (SYS_GPB_MFPH_PB12MFP_UART0_RXD | SYS_GPB_MFPH_PB13MFP_UART0_TXD);

    /* Lock protected registers */
    SYS_LockReg();
}

void UART0_Init(void)
{

    /* Configure UART0 and set UART0 baud rate */
    UART_Open(UART0, 115200);
}

    // This SQL is run on an SQL Server
    // declare @Variable varchar(100)
    // SET @Variable = 'This is a test'
    // select   CONVERT([varchar](256), HASHBYTES('SHA2_256', @Variable), 2) 
    // ========================================================================
    // C7BE1ED9-02FB8DD4-D48997C6-452F5D7E-509FBCDB-E2808B16-BCF4EDCE-4C07D14E

    // confirmed by 
    // https://tools.keycdn.com/sha256-online-generator
    // https://passwordsgenerator.net/sha256-hash-generator/
    // C7BE1ED902FB8DD4D48997C6452F5D7E509FBCDBE2808B16BCF4EDCE4C07D14E

int main(void)
{
  
    char * test = "This is a test";
    uint32_t size = strlen(test);    
    uint8_t * BytesDate = ( uint8_t *)test;
    uint32_t  au32OutputDigest[8] = {0};
    uint32_t * pau32OutputDigest = (uint32_t *)&au32OutputDigest[0];

    char  result[64] = {0};
    
    SYS_Init();                        /* Init System, IP clock and multi-function I/O */
    UART0_Init();                      /* Initialize UART0 */
    SYS_UnlockReg();                   /* Unlock register lock protect */

    NVIC_EnableIRQ(CRPT_IRQn);
    SHA_ENABLE_INT(CRPT);

    run_sha(BytesDate, size, pau32OutputDigest);

    sprintf(result,"%X-%X-%X-%X-%X-%X-%X-%X", au32OutputDigest[0],au32OutputDigest[1],au32OutputDigest[2],au32OutputDigest[3], au32OutputDigest[4], au32OutputDigest[5], au32OutputDigest[6], au32OutputDigest[7]);

    while (1);
}

//code`

**Comment by ychuang3** [comment]
Please fix the following code:

1. char * test = "This is a test";     is wrong
    please modify it as   char test[] = "This is a test";
2.  SHA_Open(CRPT, SHA_MODE_SHA256, SHA_IN_SWAP, 0);      use IN SWAP only

int run_sha(uint8_t * Data, uint32_t SizeBytes, uint32_t * au32OutputDigest)
{
	uint32_t u32SrcAddr = (uint32_t)&Data[0];

	printf("u32SrcAddr = 0x%x\n", u32SrcAddr);
	SHA_Open(CRPT, SHA_MODE_SHA256, SHA_IN_SWAP, 0);
	SHA_SetDMATransfer(CRPT, u32SrcAddr, SizeBytes);
	g_SHA_done = 0;
	SHA_Start(CRPT, CRYPTO_DMA_ONE_SHOT);
	while (!g_SHA_done) ;
	SHA_Read(CRPT, au32OutputDigest);

	return 0;
}


int main(void)
{
	char test[] = "This is a test";
	uint32_t size = strlen(test);    
	uint8_t * BytesDate = ( uint8_t *)test;
	uint32_t  au32OutputDigest[8] = {0};
	uint32_t * pau32OutputDigest = (uint32_t *)&au32OutputDigest[0];

	char  result[64] = {0};

	SYS_Init();                        /* Init System, IP clock and multi-function I/O */
	UART0_Init();                      /* Initialize UART0 */
	SYS_UnlockReg();                   /* Unlock register lock protect */


	NVIC_EnableIRQ(CRPT_IRQn);
	SHA_ENABLE_INT(CRPT);

	run_sha(BytesDate, size, pau32OutputDigest);

	sprintf(result, "%08X-%08X-%08X-%08X-%08X-%08X-%08X-%08X\n\n", au32OutputDigest[0],au32OutputDigest[1],au32OutputDigest[2],au32OutputDigest[3], au32OutputDigest[4], au32OutputDigest[5], au32OutputDigest[6], au32OutputDigest[7]);

	printf("\n%s\n", result);

	while (1);
}


And the execution output becomes:

C7BE1ED9-02FB8DD4-D48997C6-452F5D7E-509FBCDB-E2808B16-BCF4EDCE-4C07D14E
