### ISSUE TITLE
what is wrong with this code?

### ISSUE THREAD

**Issue by viobiscu** [OpenNuvoton/M480BSP#39]
I'm trying to force a boot from LDROM  with the code below and for some reason does not work!

`int main()
{

    SYS_Init();
    UART_Open(UART0, 115200);

    if (FMC_GetBootSource() != 1){ // 1  Is boot from LDROM.
      SYS_UnlockReg(); 
      FMC_Open();
      FMC_SetBootSource(1); //1: Boot from LDROM
      FMC_Close();
      SYS_LockReg(); 
      SYS->IPRST0 = SYS_IPRST0_CHIPRST_Msk;
  }
    printf("Hello World\n");

    while(1);

}`

**Comment by ychuang3** [comment]
Performing a CHIPRST will result in a complete chip reset, rendering FMC_SetBootSource() futile.
Please use CPURST instead,
Besides, please ensure that you have programmed the code to LDROM.
