### ISSUE TITLE
I2C_Wakeup_Slave is not working

### ISSUE THREAD

**Issue by chengsg78** [OpenNuvoton/M480BSP#4]
The  I2C Wake-up interrupt flag wont be set, when receive i2c address match.
 I2C_STATTUS1->ADMAT0= check.

**Comment by chengsg78** [comment]
I have check the code without modify, the code is not working,
 I2C_GET_WAKEUP_FLAG(I2C0) is unbale to get true.

    if(I2C_GET_WAKEUP_FLAG(I2C0))

    {

        /* Clear I2C Wake-up interrupt flag */

        I2C_CLEAR_WAKEUP_FLAG(I2C0);

        g_u8SlvI2CWK = 1;



        return;

    }

**Comment by chengsg78** [comment]
/* Check I2C Wake-up interrupt flag set or not */
    if(I2C_GET_WAKEUP_FLAG(I2C0))    // this wont not able to set

**Comment by mjchen1** [comment]
I test the sample code.
It looks like work normal.
![image](https://user-images.githubusercontent.com/29223206/60476215-4ad10b80-9cad-11e9-9451-588400d409cb.png)
